spring:
  datasource:
    username: root
    password: Devansh2005@#
    url: jdbc:mysql://localhost:3306/whatsapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: b15f7819606774c89cbc1477c9dcbf149683af67ed2ca3e875718850c39330ce
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days